USE [master]
GO

/****** Object:  Database [pm01.ekzamen]    Script Date: 15.04.2024 17:40:27 ******/
CREATE DATABASE [pm01.ekzamen]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'pm01.ekzamen', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\pm01.ekzamen.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'pm01.ekzamen_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\pm01.ekzamen_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [pm01.ekzamen].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [pm01.ekzamen] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET ARITHABORT OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [pm01.ekzamen] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [pm01.ekzamen] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET  DISABLE_BROKER 
GO

ALTER DATABASE [pm01.ekzamen] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [pm01.ekzamen] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [pm01.ekzamen] SET  MULTI_USER 
GO

ALTER DATABASE [pm01.ekzamen] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [pm01.ekzamen] SET DB_CHAINING OFF 
GO

ALTER DATABASE [pm01.ekzamen] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [pm01.ekzamen] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [pm01.ekzamen] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [pm01.ekzamen] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [pm01.ekzamen] SET QUERY_STORE = OFF
GO

ALTER DATABASE [pm01.ekzamen] SET  READ_WRITE 
GO

