//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizatory
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public System.DateTime Data_birth { get; set; }
        public int Country_ID { get; set; }
        public string Telephone { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public int PolID { get; set; }
    
        public virtual County County { get; set; }
        public virtual Gender_2 Gender_2 { get; set; }
    }
}
