//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jury
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public int PolID { get; set; }
        public string Почта { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public int County_ID { get; set; }
        public string телефон { get; set; }
        public string направление { get; set; }
        public string пароль { get; set; }
        public string фото { get; set; }
    
        public virtual County County { get; set; }
        public virtual Gender_2 Gender_2 { get; set; }
    }
}
