//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderator
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public string Email { get; set; }
        public System.DateTime Date_btith { get; set; }
        public int Country_ID { get; set; }
        public string Telephone { get; set; }
        public string Napravlenie { get; set; }
        public string Event { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
    
        public virtual County County { get; set; }
    }
}
